version: '3'

services:
  api:
    build: './src/api'
    volumes:
      - './src/api:/app'
    ports:
      - '8080:80'

  docker-push:
    image: 'tmvdl/projects:newsapi'
    build: './src/api'

  github-release:
    image: 'github-release'
    build: './src/api'
